/* DM2 pixel art. Every fighter is a 24x32 grid facing right.
   Each character maps to a colour in BASE_PALETTE, and a sprite can override any key. */
(function (root) {
  'use strict';

  var BASE_PALETTE = {
    k: '#140c1c', // outline
    x: '#2a2434', // near black fill
    w: '#ffffff',
    W: '#c8c8dc',
    g: '#8a8aa0',
    G: '#4a4a60',
    s: '#f8b888', // skin
    S: '#c87850',
    r: '#e83838',
    R: '#9a1e2a',
    o: '#ff9a2a',
    y: '#ffe14a',
    Y: '#c89418',
    b: '#3a78f0',
    B: '#1e3c9a',
    c: '#6ae4ff',
    C: '#c8f6ff',
    n: '#3cc84a',
    N: '#1a7a30',
    p: '#a64ae8',
    P: '#5a2290',
    m: '#9a5a2c',
    M: '#5c3418',
    t: '#ecd8a8',
    z: '#ff8ac8',
    l: '#b6ff4a'
  };

  var SPRITES = {
    lich: {
      pal: { G: '#34344c', g: '#5e6080', W: '#a8b0d0', B: '#18286a', b: '#2a48b4', c: '#7af0ff', C: '#d8fbff', x: '#0c0a16' },
      rows: [
        '......k..k..k...........',
        '.....kgkkgkkgk..........',
        '....kgWggWggWgk.........',
        '....kGgggggggGk.........',
        '....kGkkkkkkkGk.........',
        '....kGkcckcckGk.........',
        '....kGkxxxxxkGk.........',
        '....kGgkxxxkgGk.........',
        '.....kGgkxkgGk..........',
        '..kkk.kGgggGk.kkk.......',
        '.kWWWkkkGGGkkkWWWk......',
        '.kWkkWkBbkbBkWkkWk......',
        '.kWWWWkBbGbBkWWWWk...kCk',
        '..kkkkBbGcGbBkkkk..kCck.',
        '..kBbkGgGgGgGkbBk.kCck..',
        '..kBbkGgcgcgGkbBkkCck...',
        '..kBbkGGgGgGGkbkCck.....',
        '.kBbbkGgGgGgGkkCck......',
        '.kBbbkkGGGGGkkgGk.......',
        '.kBbbkcGkkkGckYYk.......',
        '.kBbbbkGgGgGkkYk........',
        'kBbbbbkgGgGgGkk.........',
        'kBbbbbkGgGgGgk..........',
        'kBbbbbkGGkkGGk..........',
        'kBbbbkGgGk.kGgk.........',
        'kBbbbkGGGk.kGGk.........',
        'kBbbbkgGk...kgGk........',
        'kBbbbkGGk...kGGk........',
        '.kBbbkGGk...kGGk........',
        '.kBbbkgGk...kgGk........',
        '..kkkkWGGk..kWGGk.......',
        '....kkkkkk..kkkkkk......'
      ]
    },

    skull: {
      pal: { y: '#f2e6a0', Y: '#b8a860', p: '#9a3ad0', P: '#561c86', b: '#4a86ec', B: '#2a4aa0', W: '#e8e0c8' },
      rows: [
        '.......kkkkkkk..........',
        '.....kkPpppppPkk...kkk..',
        '....kPpppppppppPk.kWWWk.',
        '....kPpkkkkkkkpPkkWkWWk.',
        '...kPpkyyyyyyykpPkWWWk..',
        '...kPpkykkykkykpPkkWk...',
        '...kPpkykkykkykpPk.kgk..',
        '...kPpkyyykyyykpPk.kgk..',
        '...kPPkkywywykkPPk.kgk..',
        '....kPPkkyyykkPPk..kgk..',
        '...kkPPPkkkkkPPPkk.kgk..',
        '..kbbkPPkbbbkPPkbbkkgk..',
        '.kbbbbkxbbbbbxkbbbkbbk..',
        '.kbBbbbkxkykxkbbbbkbbk..',
        '.kbBkbbbkyyykbbbbkkgkk..',
        '.kbBkbbbxkykxbbbbk.kgk..',
        '.kbBkkbxbbbbbxbbk..kgk..',
        '.kbbk.kkkkkkkkkk...kgk..',
        '.kbbk.kPpppppppk...kgk..',
        '..kk..kPpPpPpPpk...kgk..',
        '......kPpPkPpPpk...kgk..',
        '......kbbbkkbbbk...kgk..',
        '......kbbBk.kbbBk..kgk..',
        '......kbbBk.kbbBk..kgk..',
        '......kbbBk.kbbBk..kgk..',
        '......kbBk..kbbBk..kgk..',
        '.....kxxxk...kxxxk.kgk..',
        '.....kxxxk...kxxxk.kgk..',
        '.....kxgxk...kxgxk.kgk..',
        '....kxxxxk...kxxxxkkgk..',
        '....kxxxxk...kxxxxk.kk..',
        '....kkkkkk...kkkkkk.....'
      ]
    },

    leo: {
      pal: { r: '#e04a2a', R: '#a02818', o: '#ff8a3a', b: '#3a6ae8', B: '#1e3a98', y: '#ffd84a', c: '#9af0ff' },
      rows: [
        '.....kkkkkk.............',
        '...kkrrrrrrkk...........',
        '..krrorrrrorrk..........',
        '.krrrrrrrrrrrrk.........',
        '.krrRkkkkkkRrrk.........',
        'krrRkssssssskrrk........',
        'krrkskkssskkskrk........',
        'krrkskwssswkskrk........',
        'krrRksssSssskRrk........',
        '.krrkssskksskrrk........',
        '.krrRkssssskRrk.........',
        '..kRrkkSSSkkrRk.....kc..',
        '..kbbbskkkksbbbk...kck..',
        '.kbbbbsssssssbbbk.kck...',
        '.kbBbsSssssSssbbkkck....',
        '.kbBbkssSSssskbbkck.....',
        '.kbBbkssssssskbkcck.....',
        '.kbbbkbbbbbbbkkcck......',
        '.ksskkbBbbbBbkksk.......',
        '.kssk.kbbbbbbkkYYk......',
        '..kk..kyyyyyyk.kYk......',
        '......kbbbbbbbk.k.......',
        '......kbbBkbbBk.........',
        '......kbbBkbbBk.........',
        '......kbbBkkbbBk........',
        '......kbbBk.kbbBk.......',
        '......kssSk.kssSk.......',
        '......kssSk.kssSk.......',
        '.....kbbbBk.kbbbBk......',
        '.....kbbbBk.kbbbBk......',
        '.....kbbbbk..kbbbbk.....',
        '.....kkkkkk..kkkkkk.....'
      ]
    },

    heman: {
      pal: { y: '#ffe060', Y: '#d0a020', s: '#f0a868', S: '#b86c3c', m: '#8a5a2a', M: '#4c2c14', W: '#e0e0f0', g: '#9aa0b8' },
      rows: [
        '......kkkkkk............',
        '.....kyyyyyyk...........',
        '....kyyyyyyyyk..........',
        '....kyYyyyyyYyk.........',
        '....kyksssssskyk........',
        '....kykskssksyk.........',
        '....kyksssssskYk........',
        '....kYkssSSsskYk........',
        '.....kkssssssk..........',
        '......kksSSkk.......kWk.',
        '...kkkkGssssGkkkk..kWWk.',
        '..kgGgGkgssgkGgGgkkWWk..',
        '..kgkkkgkMMkgkkkgkWWk...',
        '..kssskMkGGkMkssskWk....',
        '.kssSskkMGGMkkssSkkk....',
        '.kssSsskMkkMksssSk......',
        '.kssksssskksssskkYYk....',
        '.kssk.kssssssk.kkYk.....',
        '.kssk.kMMMMMMk..ksk.....',
        '..kk..kMYyyYMk..kk......',
        '......kmmmmmmk..........',
        '......kmmmmmmmk.........',
        '......kmmMkmmMk.........',
        '......kssSkssSk.........',
        '......kssSkkssSk........',
        '......kssSk.kssSk.......',
        '......kssSk.kssSk.......',
        '.....kmmmMk.kmmmMk......',
        '.....kmmmMk.kmmmMk......',
        '.....kmMmMk.kmMmMk......',
        '.....kmmmmk..kmmmmk.....',
        '.....kkkkkk..kkkkkk.....'
      ]
    },

    mumm: {
      pal: { t: '#c8b890', T: '#8c7a58', r: '#c0182a', R: '#700c18', b: '#3050c8', B: '#1a2a78', y: '#ffd040' },
      rows: [
        '........kkkkkk..........',
        '.......kyyyyyyk.........',
        '......kRrrrrrrRk........',
        '.....kRrRRRRRRrRk.......',
        '.....kRkttTtttkRk.......',
        '.....kRktkktkkkRk.......',
        '.....kRktkrtkrkRk.......',
        '.....kRkttttTtkRk.......',
        '.....kRkTtTtTtkRk.......',
        '.....kRRkttTttkRRk......',
        '..kkkRRRRkkkkkRRRRkk....',
        '.kRRRbbbbbbbbbbbbRRRk...',
        '.kRrRkbbBbbybbBbbkRrRk..',
        '.kRrRktTbbyyybbTtkRrRk..',
        'kRrrRktTbbbybbbTtkkRrRk.',
        'kRrrRktTkbbbbbkTtk.kRrk.',
        'kRrrRktTkyyyyykTtk.kRrk.',
        'kRrrRkTtkbbbbbktTk.kRrk.',
        'kRrrRkkkkbbbbbkkkk..kRk.',
        'kRrrRk.kbbbBbbbk....kRk.',
        'kRrrRk.kbbbBbbbk...kRRk.',
        'kRrrRk.kbbbkbbbk..kRrk..',
        'kRrrRk.ktTtktTtk.kRrRk..',
        'kRrrRk.kTttkTttk.kRrk...',
        'kRrrRk.ktTtktTtkkRrRk...',
        'kRrrrRkkTttkTttkRrrk....',
        '.kRrrRkktTtktTtkRrk.....',
        '.kRrrrrkTttkTttkrk......',
        '..kRrrRkbbbkbbbkk.......',
        '...kRRkkbbBkbbBk........',
        '....kkkbbbBkbbbBk.......',
        '......kkkkkkkkkkk.......'
      ]
    },

    ganon: {
      pal: { s: '#7a8a68', S: '#55603f', r: '#d8482c', R: '#8a2418', x: '#2a2232', G: '#4c4260', y: '#f0c848', Y: '#a8801c', W: '#d8dce8', g: '#8a90a8', m: '#5a2c3c' },
      rows: [
        '........................',
        '........kkkkkk......k...',
        '.......kRrrrrrk....kWk..',
        '......kRrrryrrRk...kWk..',
        '......kRssssssRk...kWk..',
        '......kRkySSkyRk...kWk..',
        '......kRssSSssRk...kWk..',
        '......kRrRRRRrRk...kWk..',
        '......kRrrkkrrRk...kWk..',
        '.......kRrrrrRk....kWk..',
        '........kRrrRk.....kWk..',
        '...kkkkkkRRkkkkkk..kWk..',
        '..kGGGGGkxxxxkGGGGGkWk..',
        '.kGyyyyGkxxxxkGyyyyGkk..',
        '.kGGGGGGkxyyxkGGGGGGkYk.',
        '.kkkkkkkxxyyxxkkkkkkk...',
        '..kssk.kxxxxxxk.ksskmk..',
        '..kssk.kxGxxGxk.ksskmk..',
        '..kssk.kYyyyyYk.kSSkyk..',
        '..kSSk.kxxxxxxk..kk.....',
        '...kk..kxxxxxxk.........',
        '.......kxxxkxxxk........',
        '.......kxxGkxxGk........',
        '.......kxxGkxxGk........',
        '.......kxxGkkxxGk.......',
        '.......kxxGk.kxxGk......',
        '.......kGGGk.kGGGk......',
        '.......kxxGk.kxxGk......',
        '......kxxxGk.kxxxGk.....',
        '......kYyyYk.kYyyYk.....',
        '.....kxxxxxk.kxxxxxk....',
        '.....kkkkkkk.kkkkkkk....'
      ]
    },

    browser: {
      pal: { n: '#54b834', N: '#2c7018', y: '#ffd860', Y: '#c09820', r: '#ff5a28', R: '#b02c10', t: '#f8e0a0', T: '#c8a868', W: '#f0f0f0' },
      rows: [
        '..........kRk...........',
        '.........kRrRk..........',
        '.....kk.kRrrrRk.kk......',
        '....kWWkkrrRrrkkWWk.....',
        '.....kWWknnnnnkWWk......',
        '......kknnnnnnnkkk......',
        '.....knnnkwknwknnnk.....',
        '.....knnnkrkkrknnnnk....',
        '.....knnnnnnnnnnnttk....',
        '.....kNnnnnnnnnntttk....',
        '...kWkkNnnkWkWkttttk....',
        '..kWkYYkkNnnnnkkkkk.....',
        '.kWkYyyyYkkkkkttttk.....',
        '.kkYyWyyyYknnkttttnk....',
        'kWkYyyyWyYknnnkttknnk...',
        'kkYyyyyyyYknnnnkkknnnk..',
        'kWkYyWyyyYkknnnnnkknnnk.',
        '.kkYyyyyyYknnnnnnnkWnWk.',
        '..kkYyyyYkttttttttkkWkk.',
        '...kWkYYkkTtttttttk.....',
        '....kkkkkkttttttttk.....',
        '......knnkkkTtttkk......',
        '.....knnnNk.kknnNk......',
        '.....knnnNk.knnnNk......',
        '.....knnnNk.knnnNk......',
        '....knnnnNk.knnnnNk.....',
        '....knnnnNk..knnnnNk....',
        '...kWknWknk..kWknWkNk...',
        '...kkkkkkkk..kkkkkkkkk..',
        '........................',
        '........................',
        '........................'
      ]
    },

    sonik: {
      pal: { b: '#2858e8', B: '#142c90', t: '#f8d8a0', T: '#c8a068', r: '#e81c1c', R: '#981010', g: '#30c050', W: '#f0f0f0' },
      rows: [
        '........................',
        'kkk.....kkkkkk..........',
        'kbbkk.kkbbbbbbkk........',
        '.kbbbkbbbbbbbbbbk.......',
        '..kbbbbbbbbbbbbbbk......',
        'kkkbbbbbbbbbkkWWkk......',
        'kbbbbbbbbbbkWWWWWWk.....',
        '.kkbbbbbbbbkWWkgkWk.....',
        '...kbbbbbbbkWWkgkWk.....',
        'kkkbbbbbbbbbkWWWtttk....',
        'kbbbbbbbbbbbbkttttttkk..',
        '.kkbbbbbbbbbbkttttkkk...',
        '...kkbbbbbbbbkkkttk.....',
        '.....kkbbbbtttttkk......',
        '......kbbbttttttkWWk....',
        '.....kbbbbttttttkWWWk...',
        '.....kbbbktttttkWWWk....',
        '.....kbbbkttttttkkk.....',
        '......kkbbtttttbk.......',
        '........kbbbbbbbk.......',
        '........kbbbkbbbk.......',
        '........kbbk.kbbk.......',
        '........kttk.kttk.......',
        '........kttk..kttk......',
        '.......kttk...kttk......',
        '......kWrrk...krrWk.....',
        '.....kWrrrrk.krrrrWk....',
        '....kRrrWrrrkkrrrWrrk...',
        '....kRRRRRRRkkRRRRRRk...',
        '.....kkkkkkk..kkkkkkk...',
        '........................',
        '........................'
      ]
    },

    pak: {
      pal: { y: '#ffe020', Y: '#d0a000', r: '#e02828', m: '#a05020', M: '#603010' },
      rows: [
        '........................',
        '........................',
        '........kkkkkk..........',
        '......kkyyyyyykk........',
        '.....kyyyyyyyyyyk.......',
        '....kyyyyyykkyyyyk......',
        '...kyyyyyyykwkyyyyk.....',
        '...kyyyyyyykkyyykk......',
        '..kyyyyyyyyyyykk........',
        '..kyyyyyyyyykk..........',
        '..kyyyyyyykk............',
        '..kyyyyyyyyykk..........',
        '..kYyyyyyyyyyykk........',
        '...kYyyyyyyyyyyykk......',
        '...kYYyyyyyyyyyyyyk.....',
        '....kYYyyyyyyyyyyk......',
        '.....kkYYYYyyyyykk......',
        '.......kkkkkkkkk........',
        '..........kYk...........',
        '.........kYYk...........',
        '.........kYk............',
        '.........kYk............',
        '........kYk.kk..........',
        '........kYkkYk..........',
        '........kYkYk...........',
        '.......kYk.kYk..........',
        '.......kYk..kYk.........',
        '......krrrk.krrrk.......',
        '.....krrrrrkkrrrrrk.....',
        '.....kkkkkkk.kkkkkk.....',
        '........................',
        '........................'
      ]
    },

    lenk: {
      pal: { n: '#48b030', N: '#20701c', y: '#f8d850', Y: '#c09018', s: '#f8c090', S: '#c88850', m: '#8a5a2a', M: '#4c3018', b: '#3058c8', B: '#18307c', c: '#a8f0ff', W: '#e0e0f0' },
      rows: [
        '........kkkkk...........',
        '.......knnnnnk..........',
        '......knnnnnnnk.........',
        '.....knnnnnnnnnk........',
        '....knnnnnnnnnnNk.......',
        '...kyykkkkkknnnnNk......',
        '..kyyyysssssknnnNk......',
        '...kyyskkssksNnnnNk.....',
        '....kysbkssbksNnkkNk....',
        '....kssssSsssksk..kk....',
        '.....kssskksskk.....kWk.',
        '......kkssssk......kWck.',
        '..kkkkknkkkknkk...kWck..',
        '.kBbbbknnnnnnnsk.kWck...',
        'kBbbbbbknnnnnnsskWck....',
        'kBbyYbbknnnnnnkskck.....',
        'kBbYyYbknnnnnnkkck......',
        'kBbbybbkMmMMmMkYYk......',
        'kBbbbbbknnnnnnkkYk......',
        '.kBbbbbknnnnnnnkk.......',
        '..kkkkknnnnnnnnk........',
        '.......knnnnnnnnk.......',
        '.......kWWWkWWWk........',
        '.......kWWWkWWWk........',
        '.......kWWWkkWWWk.......',
        '.......kWWWk.kWWWk......',
        '......kmmmMk.kmmmMk.....',
        '......kmmmMk.kmmmMk.....',
        '......kmmmMk.kmmmMk.....',
        '.....kmmmmMk.kmmmmMk....',
        '.....kmmmmmk..kmmmmmk...',
        '.....kkkkkkk..kkkkkkk...'
      ]
    },

    mega: {
      pal: { b: '#2c88f8', B: '#1848b8', c: '#70e8ff', C: '#d0f8ff', s: '#ffc898', S: '#d88858' },
      rows: [
        '........................',
        '........kkkkkk..........',
        '......kkbbbbbbkk........',
        '.....kbbbcbbbbbbk.......',
        '....kbbbcbbbbbbbbk......',
        '....kbbckkkkkkkbbk......',
        '....kbbkssssssskbk......',
        '....kbbkwwswwssskk......',
        '....kbbkwksswksskbk.....',
        '....kbbksssssssskbk.....',
        '....kBbkssskkssskbk.....',
        '.....kBbksssssskBk......',
        '......kkkkSSSkkkk.......',
        '....kkccccccccccckkkkk..',
        '...kcccbbbbbbbbbckBBbbk.',
        '...kcckbbbbbbbbbkBbbbbbk',
        '...kcckbbbbbbbbbkBbbkkCk',
        '...kcckbbbbbbbbbkBbbkCCk',
        '....kkkccccccccckBbbbbbk',
        '.....kbbbbbbbbbbbkBbbbk.',
        '.....kccccbbbccccckkkk..',
        '.....kcccck.kcccck......',
        '.....kcccck.kcccck......',
        '.....kcccck..kcccck.....',
        '.....kcccck..kcccck.....',
        '....kbbbbbk..kbbbbbk....',
        '....kbbbbbk..kbbbbbk....',
        '...kbbbbbbk..kbbbbbbk...',
        '..kbbbbbbbk..kbbbbbbbk..',
        '..kkkkkkkkk..kkkkkkkkk..',
        '........................',
        '........................'
      ]
    },

    optimal: {
      pal: { r: '#e02020', R: '#901010', b: '#2850d8', B: '#142c80', W: '#d8dce8', g: '#9098b0', G: '#505870', c: '#6ad8ff', y: '#ffd040' },
      rows: [
        '.......k......k.........',
        '......kbk....kbk........',
        '......kbkkkkkkbk........',
        '......kbbbbbbbbk........',
        '......kbkkkkkkbk........',
        '......kbkcckcckk........',
        '......kbkWWWWWkk........',
        '......kbkWgWgWbk........',
        '......kbkWgWgWbk........',
        '...kkkkbbkkkkbbkkkk.....',
        '..kRrrrkbbbbbbkrrrrk....',
        '.kRrrrrkcccccckrrrrRk...',
        '.kRrkrrkcWccWckrrkrRk...',
        '.kRrkrrkkkkkkkkrrkrRk...',
        '.kRrkrrrrrrrrrrrrkrRk...',
        '.kbbkrrrrRkkRrrrrkbbk...',
        '.kbbkkrrrkyykrrrkkbbk...',
        '.kGGk.kkkkkkkkkk.kGGk...',
        '.kGGk.kGgggggggk.kGGk...',
        '..kk..kbbbbbbbbk..kk....',
        '......kbbbbkbbbbk.......',
        '......kbbbbkkbbbbk......',
        '.....kbbWbbk.kbbWbbk....',
        '.....kbbWbbk.kbbWbbk....',
        '.....kbbbbbk.kbbbbbk....',
        '.....kbgGgbk.kbgGgbk....',
        '.....kbgGgbk.kbgGgbk....',
        '.....kbbbbbk.kbbbbbk....',
        '....kbbbbbbk.kbbbbbbk...',
        '....kWWWWWWk.kWWWWWWk...',
        '....kGGGGGGk.kGGGGGGk...',
        '....kkkkkkkk.kkkkkkkk...'
      ]
    },

    shreddor: {
      pal: { W: '#d8dce8', g: '#9aa0b8', G: '#5a6078', p: '#9a40c8', P: '#4c1c78', r: '#d02030', m: '#8a3a28', M: '#4c1c14' },
      rows: [
        '....kk..kk..kk..........',
        '....kWk.kWk.kWk.........',
        '.....kWkkWkkWk..........',
        '.....kWWWWWWWWk.........',
        '....kWggggggggWk........',
        '....kWgkkkkkkgWk........',
        '....kWgkxxxxkkgk........',
        '....kWkkrxxrkkgk........',
        '....kWkxxxxxxkWk........',
        '....kWkkkkkkkkWk.kk.....',
        '..kkkWWWkkkkWWWkkkWk....',
        '.kWkWkgWWkkWWgkWkWWk....',
        '.kPpkWkGGkkGGkWkpkWk....',
        'kPppkkmmmkkmmmkkpppWk...',
        'kPppkmmmmMMmmmmkppkWk...',
        'kPppkmMmmmmmmMmkpkWWk...',
        'kPppkkmmMmmMmmkkkWWk....',
        'kPppkWgkmmmmmkgWkWk.....',
        'kPppkWWkkkkkkkWWkk......',
        'kPppPkkGkkkkkGkk........',
        'kPppPpkGGGkGGGk.........',
        'kPpppPkxxxxkxxxk........',
        'kPppppkxxxxkkxxxk.......',
        'kPppppkxxGkk.kxxxk......',
        '.kPpppkxxGk..kxxGk......',
        '.kPpppkxxGk..kxxGk......',
        '..kPppkWWGk..kWWGk......',
        '..kPppkxxGk..kxxGk......',
        '...kPkkxxGk..kxxGk......',
        '....kkxxxGk..kxxxGk.....',
        '.....kxxxxk..kxxxxxk....',
        '.....kkkkkk..kkkkkkk....'
      ]
    },

    turtle: {
      pal: { n: '#5cc040', N: '#2c7a1c', b: '#2c68e8', B: '#183c98', m: '#b07830', M: '#704818', y: '#f0d070', Y: '#b89838', W: '#d8e0f0', g: '#8890a8' },
      rows: [
        '..............kWk.......',
        '.......kkkkk..kWk.......',
        '.....kknnnnnkkkWk.......',
        '....knnnnnnnnnkgk.......',
        '...kbbbbbbbbbbbbkk......',
        '..kbbbbkwkbbkwkbbbk.....',
        '..kbbbbkkkbbkkkbbbbk....',
        '...knbbbbbbbbbbbbkbbk...',
        '...knnnnnnnnnnnnk..kbk..',
        '...knnnnkkkkknnnk...k...',
        '....knnnnnnnnnnk........',
        '..kmkknnnnnnnnkkk.......',
        '.kmmmkkMkkkkkMkkMk......',
        'kmmMmmkyyyyyyyykMMk..kk.',
        'kmMmmmkyYyyyYyyknnk.kWk.',
        'kmmmmMkyyyyyyyyknnkkWk..',
        'kMmmmmkyYyyyYyyknNkWk...',
        'kmmMmmkyyyyyyyykkkgkk...',
        '.kmmmkkyYyyyYyyknnk.....',
        '..kkk.kbbbbbbbbkNk......',
        '......kyyyyyyyyk........',
        '.......knnnnnnnk........',
        '......knnnkknnnk........',
        '......knnNk.knnNk.......',
        '......kbbbk.kbbbk.......',
        '......knnNk.knnNk.......',
        '......knnNk.knnNk.......',
        '.....knnnNk.knnnNk......',
        '.....knnnNk.knnnNk......',
        '....knnnnNk.knnnnNk.....',
        '....knnnnnk..knnnnnk....',
        '....kkkkkkk..kkkkkkk....'
      ]
    },

    ryo: {
      pal: { W: '#f0f0f0', g: '#b8b8c8', r: '#e02828', m: '#4a2a14', s: '#f8b880', S: '#c87848', x: '#20180c' },
      rows: [
        '........................',
        '.......kkkkkkk..........',
        '......kmmmmmmmk.........',
        '.....kmmmmmmmmmk........',
        '.....krrrrrrrrrkk.......',
        '....kkmssssssmkrrk......',
        '....kmssssssssk.rrk.....',
        '....kmskkssskksk..k.....',
        '....kmsswsssswsk........',
        '....kmsssSssssSk........',
        '.....kssskkksSk.........',
        '......kssssssk..........',
        '...kkkkkSSSSkkkkk.......',
        '..kWWWWkkWWkkWWWWkk.....',
        '.kWWgWWWkkkkWWWWgWWk....',
        '.kWWkgWWWsssWWWkkgWWk...',
        '.kWWk.kWWsSsWWk..kkssk..',
        '.ksskk.kWWWWWk...kssssk.',
        '.ksssk.kxxxxxk....kssk..',
        '..kkk..kWWWWWWk....kk...',
        '......kWWWWWWWWk........',
        '......kWWgkkWWWk........',
        '.....kWWWgk.kWWWk.......',
        '.....kWWWgk.kWWWk.......',
        '....kWWWWgk..kWWWk......',
        '....kWWWgk...kWWWWk.....',
        '....kWWWgk....kWWWk.....',
        '....kkkkkk....kkkkk.....',
        '....kssssk....kssssk....',
        '...ksssssk....ksssssk...',
        '...kkkkkkk....kkkkkkk...',
        '........................'
      ]
    },

    scorpyon: {
      pal: { y: '#f8d020', Y: '#b88c10', x: '#1c1c24', G: '#3a3a48', s: '#e8a070', W: '#ffffff', g: '#9aa0b0' },
      rows: [
        '........................',
        '.......kkkkkkk..........',
        '......kyyyyyyyk.........',
        '.....kyyyyyyyyyk........',
        '.....kyykkkkkkkk........',
        '.....kyykWkkWkkk........',
        '.....kyykxxxxxkk........',
        '.....kxxxxxxxxxk........',
        '.....kxxGxxxGxxk........',
        '.....kkxxxxxxxkk........',
        '......kkyyyyykk.........',
        '..kkkkyyyyyyyyykkkk.....',
        '.kyyyYyyxxxxxyyYyyyk....',
        '.kyykYyxxxxxxxyYkyyk....',
        '.kyykyyyxxxxxyyyykyyk...',
        '.kxxkkyyyyxyyyyykkxxk...',
        '.kxxk.kYyyyyyyYk.kxxkk..',
        '.kxxk.kxxxxxxxxk.kxxgWk.',
        '..kk..kYYYyYYYYk..kkgk..',
        '.....kxxxxxxxxxk...kgk..',
        '.....kxxxxkkxxxk..kgk...',
        '.....kyyyyk.kyyyyk.kgk..',
        '.....kyyyYk.kyyyYk..kgk.',
        '.....kyyyYk.kyyyYk...kg.',
        '.....kxxxGk.kxxxGk....k.',
        '.....kxxxGk.kxxxGk......',
        '.....kyyyYk.kyyyYk......',
        '.....kyyyYk.kyyyYk......',
        '....kxxxxGk.kxxxxGk.....',
        '....kxxxxxk..kxxxxxk....',
        '....kkkkkkk..kkkkkkk....',
        '........................'
      ]
    },

    samos: {
      pal: { o: '#f08a20', O: '#a85010', r: '#d03018', R: '#802010', y: '#f8d838', Y: '#b89818', n: '#50f070', N: '#20a040', g: '#909aa8', G: '#505868' },
      rows: [
        '........................',
        '........kkkkkk..........',
        '.......krrrrrrkk........',
        '......krrrrrrrrrk.......',
        '.....krrrkkkkkrrrk......',
        '.....krrknnnnnkrrk......',
        '.....krrknNnnnkrrk......',
        '.....krrknnnnNkrrk......',
        '.....kRrrkkkkkrrRk......',
        '...kkkkRrrrrrrrRkkkk....',
        '..kooookRRRRRRkooooork..',
        '.koooOOokyyyykkooooOOk..',
        '.kooOOookYyyYkkooooook..',
        '.koooookrrrrrrkkkkkkkkk.',
        '..kkkkkrrRrrRrkggGgggggk',
        '...kkrrrrrrrrrkgGkkkkkkk',
        '..krrkrrrrrrrrkGGnnnnnk.',
        '..krrkkyyyyyykkgGgggggk.',
        '..krrk.krrrrrrkkkkkkkk..',
        '...kk..kGGGGGGk.........',
        '......kooookooook.......',
        '......kooOkkooOOk.......',
        '......kroOk.kroOk.......',
        '......kroOk.kroOk.......',
        '......kooOk.kooOk.......',
        '.....kooooOkkooooOk.....',
        '.....krrrrRkkrrrrRk.....',
        '.....krrrrRkkrrrrRk.....',
        '....krrrrrRk.krrrrRk....',
        '....kooooooOk.kooooooOk.',
        '....kkkkkkkkk.kkkkkkkkk.',
        '........................'
      ]
    },

    kongo: {
      pal: { m: '#8c4a1c', M: '#542a0c', t: '#e8b080', T: '#b07850', r: '#e02828', R: '#901818', y: '#ffd040' },
      rows: [
        '........................',
        '........................',
        '.......kkkkkkk..........',
        '.....kkMmmmmmMkk........',
        '....kMmmmmmmmmmMk.......',
        '...kMmmmmmmmmmmmMk......',
        '...kMmkttttkttttkk......',
        '...kmkttkwtttkwtk.......',
        '...kmkttkktttkktk.......',
        '...kmkttttttttttk.......',
        '...kmmkttkttkttttk......',
        '..kkmmktttttttttttk.....',
        '.kMmmmmktkkkkkkttk......',
        'kMmmmmmmktttttttkmmkk...',
        'kMmmkmmmmkkkkkkkmmmmmk..',
        'kMmkmmmmmmrrrmmmmmmmmmk.',
        'kmmkmmmmmmmrRrmmmmkmmmk.',
        'kmmkmmmtttmrRrtttmkmmmk.',
        'kmmkmmmtttmRrRtttmkmmmk.',
        'kttkmmmmttttyttttmkkttk.',
        'kttkkmmmmmtttttmmmk.kttk',
        'kttttkmmmmmmmmmmmmk.kttk',
        '.kkkkkmmmmmmmmmmmmk..kk.',
        '.....kmmmmmkkmmmmmk.....',
        '.....kmmmmk..kmmmmk.....',
        '.....kmmmmk..kmmmmk.....',
        '.....kmmmMk..kmmmMk.....',
        '....kmmmmMk..kmmmMMk....',
        '...kttttTk...kttttTk....',
        '...kkkkkkk...kkkkkkk....',
        '........................',
        '........................'
      ]
    },

    kobra: {
      pal: { b: '#2c5ad8', B: '#16307c', W: '#e8eef8', g: '#a8b4c8', r: '#e02020', R: '#901010', c: '#a8d8ff', G: '#4a5468' },
      rows: [
        '........................',
        '........kkkkkk..........',
        '......kkbbbbbbkk........',
        '.....kbbbbbbbbbbk.......',
        '....kbbbbbbbbbbbbk......',
        '....kbbkkkkkkkkbbk......',
        '....kbbkcWcWcWkbbk......',
        '....kbbkWcWcWckbbk......',
        '....kbbkcWcWcWkbbk......',
        '....kbbkWcWcWckbbk......',
        '....kBbbkkkkkkbbBk......',
        '...kkBbbbbbbbbbBkkk.....',
        '..kbbkBBbbbbbbBBkbbk....',
        '.kbbbbkkBbrrbBkkbbbbk...',
        '.kbbbbbbkrRRrkbbbbbbk...',
        '.kbbkbbbbkrrkbbbbkbbk...',
        '.kbbkbbbbbkkbbbbbkbbk...',
        '.kbbkbbbbbbbbbbbbkbbk...',
        '.kGGkkkkkkkkkkkkkkGGk...',
        '.kGGk.kbbbbbbbbbk.kGGkk.',
        '..kk..kGGGGyGGGGk..kbbk.',
        '......kbbbbbbbbbk...kk..',
        '......kbbbbkbbbbk.......',
        '......kbbbBkkbbbBk......',
        '......kbbbBk.kbbbBk.....',
        '......kbbbBk.kbbbBk.....',
        '......kbbbBk.kbbbBk.....',
        '.....kxxxxGk.kxxxxGk....',
        '.....kxxxxGk.kxxxxGk....',
        '....kxxxxxGk.kxxxxxGk...',
        '....kkkkkkkk.kkkkkkkk...',
        '........................'
      ]
    },

    robutnik: {
      pal: { r: '#e02020', R: '#901010', s: '#ffc898', S: '#d88858', m: '#f08828', M: '#a85010', x: '#1c1c28', y: '#ffd840', c: '#80d8ff' },
      rows: [
        '........................',
        '.........kkkkkk.........',
        '.......kksssssskk.......',
        '......kssssssssssk......',
        '......kssssssssssk......',
        '.....kkxxxxkxxxxkk......',
        '.....kxcckxkxcckxk......',
        '.....kxxxxkkxxxxksk.....',
        '.....kssssssssSssssk....',
        '...kkmmmmmssssmmmmmkk...',
        '..kmmmmmmmMSSMmmmmmmmk..',
        '..kMMMkkmmmmmmmmkkMMMk..',
        '...kkk.ksssssssskk.kk...',
        '.....kkkkkkkkkkkkkk.....',
        '...kkrrrrrkxxkrrrrrkk...',
        '..krrrrrrrkxxkrrrrrrrk..',
        '.krrrrrrrrrkkrrrrrrrrrk.',
        '.krrrkrrrrrrrrrrrrkrrrk.',
        'krrrrkrrrrrrrrrrrrkrrrrk',
        'krrrkrrrrrRyRrrrrrrkrrrk',
        'kWWWkrrrrrrrrrrrrrrkWWWk',
        'kWWWkkrrrrrrrrrrrrkkWWWk',
        '.kkk.kxxxxxxxxxxxxk.kkk.',
        '.....kxxxxxxxxxxxxk.....',
        '......kxxxxkkxxxxk......',
        '......kxxxk..kxxxk......',
        '......kxxxk..kxxxk......',
        '......kxxxk..kxxxk......',
        '.....kxxxxk..kxxxxk.....',
        '....kxxxxxk..kxxxxxk....',
        '....kkkkkkk..kkkkkkk....',
        '........................'
      ]
    },

    septi: {
      pal: { W: '#eef0f6', g: '#a8b0c4', s: '#f4d0b0', S: '#c89878', x: '#1a1622', G: '#3a3446', n: '#60e080', Y: '#8a6a3a', C: '#e8f8ff', c: '#9ab8d0' },
      rows: [
        '........................',
        '.........kkkkk..........',
        '........kWWWWWkk........',
        '.......kWWWWWWWWk.......',
        '......kWWWgWWgWWk......c',
        '......kWWgssssgWk......C',
        '......kWgsnssnsWk.....c.',
        '......kWgssSsssWk.....C.',
        '......kWWssksssWk....c..',
        '...kWWkWWkssskWWk....C..',
        '...kWWkWWWkkkWWWk...c...',
        '...kWgkkxxGsssGxxk..C...',
        '...kWkgggkxGsSGxkggc....',
        '...kWkgWgkxxGsGxxkgCgk..',
        '...kWkgggkxxGsGxxkcggk..',
        '...kWgkxxkxxxsxxxkCxk...',
        '...kWWkxxkxYYYYYxcxsk...',
        '...kWgkssk.xxxxkYkssk...',
        '...kWWkssk.xxxGxkkkk....',
        '...kWk.kk.kxxxkxxxk.....',
        '...kk.....kxxxkGxxk.....',
        '..........kxxGkkxxGk....',
        '..........kxxGk.kxxGk...',
        '.........kxxxGk.kxxxk...',
        '.........kxxxGk..kxxGk..',
        '.........kxxGGk..kxxGk..',
        '.........kxxGk...kxxGk..',
        '.........kxxGk...kxxGk..',
        '........kxxxGk...kxxxGk.',
        '........kxxxxk...kxxxxk.',
        '........kkkkkk...kkkkkk.',
        '........................'
      ]
    },

    megatrom: {
      pal: { g: '#a8b0c0', G: '#5a6274', W: '#dce2ee', x: '#26282e', r: '#ff3030', p: '#8a48d0' },
      rows: [
        '........................',
        '..........kkkk..........',
        '.........kgWWgk.........',
        '........kgWWWWgk........',
        '.......kgWgWWgWgk.......',
        '.......kgWkkkkWgk.......',
        '.......kgkrkkrkgk.......',
        '.......kgkWWWWkgk.......',
        '.......kgkWGGWkgk.......',
        '........kgkWWkgk........',
        '.........kkkkkk.........',
        '.....kkkkkkkkkkkkk......',
        '....kgggkWWWWWkgggk.....',
        '...kgWWgkWpWpWkgWWgk....',
        '...kgggkkWWpWWkkkkkkkk..',
        '...kGGk.kWWWWWkxxxxxxxrk',
        '...kggk.kGGGGGkxGGGGGxxk',
        '...kggk.kgggggkxxxxxxxkk',
        '...kWWk.kgGkGgkkkkkkkk..',
        '....kk..kgggkggk.kk.....',
        '........kgggkgggk.......',
        '........kgWgkgWgk.......',
        '........kgggkgggk.......',
        '........kGGGkGGGk.......',
        '........kgggkkgggk......',
        '.......kgggk.kgggk......',
        '.......kgWgk.kgWgk......',
        '.......kgggk.kgggk......',
        '......kGGGGk.kGGGGk.....',
        '......kgggggk.kgggggk...',
        '......kGGGGGk.kGGGGGk...',
        '......kkkkkkk.kkkkkkk...'
      ]
    },

    clara: {
      pal: { m: '#6a3a1a', M: '#40220e', s: '#f0b890', S: '#c08060', c: '#30a8b0', C: '#1e6a70', t: '#a88050', T: '#705030', x: '#2a2a2a', G: '#4a4a4a', Y: '#7a5028', z: '#c85a60' },
      rows: [
        '........................',
        '..........kkkkk.........',
        '.........kmmmmmk........',
        '........kmmmmmmmk.......',
        '........kmmsssssk.......',
        '........kmskssksk.......',
        '......kmkmssssSsk.......',
        '......kMkmssszssk.......',
        '......kmkkmsssskk.......',
        '......kMk.kkSSk.........',
        '......kmkkssssk.........',
        '......kMksscccsskkkkkkkk',
        '......kkssccccccsssssxxk',
        '......kksskccccCkkkkkkxk',
        '......kkssk.kcCcck....k.',
        '......kkssk.kcccck......',
        '......kkSSk.kYYYYk......',
        '.......kkk..ktttttk.....',
        '...........kttTkttk.....',
        '...........kxYTkxYk.....',
        '...........kssSkssSk....',
        '...........kssSkkssSk...',
        '...........kssSk.kssSk..',
        '...........kssSk.kssSk..',
        '...........kssSk.kssSk..',
        '...........kxxGk.kxxGk..',
        '..........kxxxGk.kxxxGk.',
        '..........kxxxGk.kxxxGk.',
        '.........kxxxxGk.kxxxxGk',
        '.........kxxxxxk.kxxxxxk',
        '.........kkkkkkk.kkkkkkk',
        '........................'
      ]
    },

    chief: {
      pal: { n: '#5a7a3a', N: '#3a5226', l: '#8aaa5a', y: '#ffb830', Y: '#c07810', w: '#fff0c0', G: '#4a4a52', x: '#26262c', g: '#8a8a94' },
      rows: [
        '........................',
        '..........kkkkk.........',
        '.........knnnnnk........',
        '........knllnnnnk.......',
        '.......knlnnnnnnNk......',
        '.......knkyyyyyykk......',
        '.......knkyYwyyYYk......',
        '.......knnkkkkkkNk......',
        '.......kNnnnnnnNk.......',
        '........kkNNNNNkk.......',
        '.....kkkkkkkkkkkkk......',
        '....knnnnkGGGGknnnnk....',
        '...knllnnkGGGGknnlnNk...',
        '...knnnnNknnnnkNnnnNk...',
        '...kNnnNkknlnnkkNnnNk...',
        '....kkkk.knnnNkkkkkkkkkk',
        '....kNnk.kNnkkxxxgxxxxxk',
        '....kGGk.kGGkxxxgggxxxxk',
        '.....kk..kxYkkkxkkxkkkkk',
        '........kNnnnNNkxk......',
        '........knnNknnNk.......',
        '........knnNknnNk.......',
        '........kGGGkGGGk.......',
        '........knlnkknlnk......',
        '.......knnnNk.knnNk.....',
        '.......knnnNk.knnNk.....',
        '.......kGGGGk.kGGGk.....',
        '.......knnnNk.knnnNk....',
        '......knnnnNk.knnnnNk...',
        '......kNNNNNk.kNNNNNk...',
        '......kkkkkkk.kkkkkkk...',
        '........................'
      ]
    },

    malfur: {
      pal: { p: '#9a70d0', P: '#6a48a0', n: '#4ac080', N: '#2a8050', m: '#7a5030', M: '#4a2a14', W: '#e8e0c8', g: '#9a8a6a', c: '#2a8a7a', C: '#1c5e54', y: '#e8f8a0' },
      rows: [
        '..k..k.........k..k.....',
        '..km.mk.......km.mk.....',
        '...kmmk.k...k.kmmk......',
        '....kmmkmkkkkkkmk...kyk.',
        '.....kkmknnnnnnk...kyyyk',
        '.......knnppppnnk...kyk.',
        '.......knppppppnk...kmk.',
        '.......knpyypyypk...kmk.',
        '.......knppPPpppk...kmk.',
        '.......knpnnnnnpk...kmk.',
        '.......knnnPPnnnk...kmk.',
        '.......knnnnnnnnk...kmk.',
        '...kkkk.knkknnnkkkk.kmk.',
        '...kWgWkkcnnckkWgWk.kmk.',
        '...kgWgkcccncckgWgk.kmk.',
        '...kWgWkcCcccCkWgWk.kmk.',
        '....kkkkcMMMMckkkk..kmk.',
        '....kppkcccccck.kppkkmk.',
        '....kpPkcCcccck.kpPkkmk.',
        '....kPPkcccccck..kk.kmk.',
        '.....kk.kcccccck....kmk.',
        '........kcCcccck....kmk.',
        '........kccccccck...kmk.',
        '........kcCcccccck..kmk.',
        '........kccccccccck.kmk.',
        '........kMMMMkMMMMk.kmk.',
        '.......kmmmMk.kmmmMkkMk.',
        '.......kmmmMk.kmmmMk.k..',
        '.......kmmmmk.kmmmmk....',
        '.......kkkkkk.kkkkkk....',
        '........................',
        '........................'
      ]
    },

    snack: {
      pal: { b: '#5a6a8a', B: '#38425e', G: '#3a3a40', x: '#1e1e24', m: '#5a3a20', M: '#3a2414', s: '#e8b088', S: '#b07850', N: '#1a2440', g: '#8a8a90' },
      rows: [
        '........................',
        '.........kkkkkk.........',
        '........kmmmmmmk........',
        '..kNNk.kmmmmmmmmk.......',
        '...kNNkkNNNNNNNNk.......',
        '....kNkkmsssssssk.......',
        '.....kNNkskssksSk.......',
        '.......kmssssSssk.......',
        '.......kmSSSkSSSk.......',
        '........kmSSSSSk........',
        '.........kkSSkk.........',
        '......kkkkkkkkkk........',
        '.....kbbbkbbbbkbbbk.....',
        '....kbBbbkGbbGkbbBbk....',
        '....kbbbkbGGGGbkbbbk....',
        '....kbbbkbbbbbbkkbbbk...',
        '....kbbk.kGxGxGk.kbbbkkk',
        '....kbbk.kbbbbbk.kbsggxk',
        '....kGGk.kGGGGGk..kkkkxk',
        '.....kk..kbbbbbk........',
        '.........kbbbkbbk.......',
        '.........kbbBkbbBk......',
        '.........kGxBkGxBk......',
        '.........kbbBkkbbBk.....',
        '.........kbbBk.kbbBk....',
        '........kbbbBk.kbbbBk...',
        '........kbbbBk.kbbbBk...',
        '........kxxxGk.kxxxGk...',
        '.......kxxxxGk.kxxxxGk..',
        '.......kxxxxxk.kxxxxxk..',
        '.......kkkkkkk.kkkkkkk..',
        '........................'
      ]
    },

    sorta: {
      pal: { m: '#8a5220', M: '#4a2810', s: '#f8c8a0', S: '#d09070', b: '#3a7ae8', r: '#d82828', R: '#901818', x: '#20202a', W: '#f0f0f0', y: '#ffd840', Y: '#c09818', g: '#c8ccd8', G: '#7a7e8c' },
      rows: [
        '......k..k...k..........',
        '.....kmk.kmk.kmk..k.....',
        '.....kmmkkmmkkmmkkmk....',
        '....kmmmmmmmmmmmmmmk..kg',
        '.....kmmmmmmmmmmmmk..gkg',
        '....kmmmmmmmmmmmmmk..gg.',
        '.....kmmkmsssssskmmk..g.',
        '.......kmsbksbksk....G..',
        '.......kmsbksbksk....g..',
        '.......kmssssssSk...G...',
        '........kmsskssk....g...',
        '.........kksssk....G....',
        '.......kkkkkkkk....g....',
        '......kxxkyykxxk..G.....',
        '.....kxxxkWWkxxxk.g.....',
        '.....kxkkrrrrkkkYYk.....',
        '.....kssk.krrrrkkykk....',
        '.....kssk.kRrrrkkkssk...',
        '.....kssk.kxxxxk..kk....',
        '......kk.kRrrrrRk.......',
        '.........krrrrrrrk......',
        '.........krrRkrrRk......',
        '.........krrRkkrrRk.....',
        '.........kRRk..kRRk.....',
        '..........kssk.kssk.....',
        '..........kssk.kssk.....',
        '.........kyyyk.kyyyk....',
        '........kyyyyYkkyyyyYk..',
        '.......kyyyyyYkkyyyyyYk.',
        '.......kkkkkkkk.kkkkkkk.',
        '........................',
        '........................'
      ]
    }
  };

  function paletteFor(id) {
    var s = SPRITES[id];
    var pal = {};
    for (var k in BASE_PALETTE) pal[k] = BASE_PALETTE[k];
    if (s && s.pal) for (var j in s.pal) pal[j] = s.pal[j];
    return pal;
  }

  /* Returns an array of {x, y, c} for every opaque pixel. */
  function pixels(id) {
    var s = SPRITES[id];
    var pal = paletteFor(id);
    var out = [];
    var bottom = 0;
    for (var by = 0; by < 32; by++) if (/[^.\s]/.test(s.rows[by] || '')) bottom = by;
    var shift = 31 - bottom; // stand every fighter on the same floor line
    for (var y = 0; y < 32; y++) {
      var row = s.rows[y] || '';
      for (var x = 0; x < 24; x++) {
        var ch = row.charAt(x);
        if (!ch || ch === '.' || ch === ' ') continue;
        out.push({ x: x, y: y + shift, c: pal[ch] || '#ff00ff' });
      }
    }
    return out;
  }

  var api = { SPRITES: SPRITES, BASE_PALETTE: BASE_PALETTE, pixels: pixels, W: 24, H: 32 };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else { root.DM2 = root.DM2 || {}; root.DM2.sprites = api; }
})(this);
